paths:
  /products:
    post:
      summary: Salva um novo produto
      tags: [product]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        201:
          description: Produto cadastrado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  product:
                    $ref: "#/components/schemas/ProductCreatedResponse"
        400:
          description: O objeto de Produto recebido é inválido
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/ProductCreationFailResponse"

